apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: my-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - image: mongo-express
        name: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: my-mongo-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: my-mongo-secret
                key: mongo-root-password
              
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: my-mongo-configmap
                key: mongo-db-url


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-express-service
  name: my-express-service
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30001
  selector:
    app: mongo-express


              
