apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
  namespace: fluent
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "pods", "namespaces"]
  verbs: ["get", "list", "watch"]
