apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File parsers.conf

    @INCLUDE input-*.conf
    @INCLUDE output-*.conf

    @INCLUDE filters.conf
  
  parsers.conf: |
    [PARSER]
        Name        azure_blob
        Format      json
        Time_Key    requestReceivedTimestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On
    [PARSER]
        Name        kubernetes-tag
        Format      regex
        Regex       (?<namespace_name>.+)\.(?<pod_name>.+)\.(?<container_name>.+)


  input-s3logs.conf: |
    ## AWS S3 configuration
    # [INPUT]
    #     Name              tail
    #     Tag               kube.fluent.nginx-deployment.nginx
    #     Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
    #     Path              /var/log/containers/*.log
    #     Exclude_Path      /var/log/containers/*_fluent_*.log
    #     Parser            s3_logs
    #     DB                /var/log/flb_kube.db
    #     Mem_Buf_Limit     5MB
    #     Skip_Long_Lines   On
    #     Refresh_Interval  10

    [INPUT]
        Name              tail
        Tag               kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*_fluentbit2S3_*.log

  output-s3.conf: |
    ## AWS S3 configuration
    # [OUTPUT]
    #     Name s3
    #     Match *
    #     bucket /myminiobucket/
    #     region us-east-2
    #     use_put_object On
    #     s3_key_format /fluent-bit-logs/$TAG/%Y/%m/%d/%H/%M/%S
    #     s3_key_format_tag_delimiters . 
    #     total_file_size 5M
    #     upload_timeout 1m
    
    # [OUTPUT]
    #     Name  stdout
    #     Match *

    ## Azure blob configuration
    [OUTPUT]
        Name azure_blob
        Match *
        account_name testairbyte001
        shared_key P9awwev4fiaQMdqo7V950ifyRW0AV51/lqXvcuQ+of07TpTS3ghyLGmoFDqaodGq+hfvZJmrdGGf+AStFRKYKA==
        container_name test-fluentbit
        path kubernetes
        # blob_type blockblob
        auto_create_container on
        tls on


  filters.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://172.20.18.200:6443
        # Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        # Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  Off
        K8S-Logging.Exclude Off
        # Regex_Parser        kubernetes-tag
        Labels              Off
        Annotations         Off
